[package]
name = "bmd-speededitor"
version = "0.1.0"
authors = ["Akira Kamikura <akira.kamikura@gmail.com>"]
edition = "2021"

[workspace]
members = [
    "examples/basic"
]

[dependencies]
hidapi = "1.4.1"
chrono = "0.4"
