[package]
name = "bmd-speededitor"
version = "0.1.4"
authors = ["Akira Kamikura <akira.kamikura@gmail.com>"]
edition = "2021"

[workspace]
members = [
    "examples/basic"
]

[dependencies]
hidapi = "1.4.1"
chrono = "0.4"
num_enum = "0.5"
strum = "0.24"
strum_macros = "0.24"
